name = "api-magiccap-org"
main = "src/index.ts"
compatibility_date = "2022-04-16"

[durable_objects]
bindings = [{name = "UPDATES", class_name = "Updates"}]

[env]
API_TOKEN = ""
S3_HOSTNAME = ""
S3_ENDPOINT = ""
S3_ACCESS_KEY_ID = ""
S3_SECRET_ACCESS_KEY = ""
S3_BUCKET = ""

[[migrations]]
tag = "v1"
new_classes = ["Updates"]
